In [3]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.impute import MissingIndicator
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
df = pd.read_csv("titanic_toy.csv")
x= df.drop(columns ="Survived")
y=df["Survived"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state =42)

In [15]:
from sklearn.impute import MissingIndicator

mi = MissingIndicator(features='all')
x_train_mi = mi.fit_transform(x_train[["Age"]])
x_test_mi = mi.transform(x_test[["Age"]])

x_train["Age_na"] = x_train_mi.ravel()   # convert 2D -> 1D
x_test["Age_na"] = x_test_mi.ravel()

In [16]:
x_train

      Age      Fare  Family  Age_na
331  45.5   28.5000       0   False
733  23.0   13.0000       0   False
382  32.0    7.9250       0   False
704  26.0    7.8542       1   False
813   6.0   31.2750       6   False
..    ...       ...     ...     ...
106  21.0    7.6500       0   False
270   NaN   31.0000       0    True
860  41.0       NaN       2   False
435  14.0  120.0000       3   False
102  21.0   77.2875       1   False

[712 rows x 4 columns]

In [25]:
# Use SimpleImputer with indicator
imputer = SimpleImputer( add_indicator=True)

# Fit on train
x_train_m1 = imputer.fit_transform(x_train)
x_test_m2 = imputer.transform(x_test)

In [29]:
x_train_m1 = pd.DataFrame()